version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/python:3.6.1
     
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
           
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            sudo apt-get install libasound-dev portaudio19-dev libportaudio2 libportaudiocpp0
            sudo apt-get install ffmpeg libav-tools
            sudo -s
            python3 -m pip install pyaudio
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
          
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      # - test
